### ISSUE TITLE
Провести проверку на большом файле

### ISSUE THREAD

**Issue by alexkoss** [EDyugaeva/ReadingFileApp#2]
Добрый день! Меня зовут Александр, представитель компании БалтИнфоКом.

Предлагаю осуществить проверку на большом файле.

Файл: https://github.com/PeacockTeam/new-job/releases/download/v1.0/lng-big.7z

В ответе должно быть количество групп и время выполнения.

**Comment by EDyugaeva** [comment]
Добрый день!
Количество групп = 105036
Время выполнения программы = 6,483 с
Если выводить все группы в консоль дополнительно к созданию файла, время = 68,904с
